### ISSUE TITLE
UITabBarButton elements on iOS not being detected

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#153]
I've got a tab bar in my app with five separate buttons, all of which have Accessibility IDs and can be queried using Sherlock - they are UITabBarButtons with UITabBarButtonLabels.

I'm unable to tap on these and they are not showing in the app Hierarchy on Maestro:

![Screenshot 2022-09-09 at 17 10 57](https://user-images.githubusercontent.com/74550141/189394487-3be58078-e09b-446d-8a2d-79fc8f04ce5a.png)

**Comment by dmitry-zaitsev** [comment]
Could you please share an output of `idb ui describe-all` command? That is what we use under the hood to find elements on screen

**Comment by simon-gilmurray** [comment]
@dmitry-zaitsev 
`idb ui describe-all
[{"AXFrame":"{{0, 0}, {390, 844}}","AXUniqueId":null,"frame":{"y":0,"x":0,"width":390,"height":844},"role_description":"application","AXLabel":"<appname>","content_required":false,"type":"Application","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXApplication","subrole":null},{"AXFrame":"{{336, 50}, {38, 38}}","AXUniqueId":"account_switcher_button","frame":{"y":50,"x":336,"width":38,"height":38},"role_description":"button","AXLabel":"Account menu","content_required":false,"type":"Button","title":null,"help":null,"custom_actions":["Open account switcher"],"AXValue":null,"enabled":true,"role":"AXButton","subrole":null},{"AXFrame":"{{142.33333333333334, 113}, {105.66666666666666, 32}}","AXUniqueId":"pillSwitcher","frame":{"y":113,"x":142.33333333333334,"width":105.66666666666666,"height":32},"role_description":"button","AXLabel":"Personal account","content_required":false,"type":"Button","title":null,"help":"Double tap to switch account","custom_actions":[],"AXValue":null,"enabled":true,"role":"AXButton","subrole":null},{"AXFrame":"{{91.333333333333329, 153}, {207.66666666666669, 40.666666666666657}}","AXUniqueId":"balanceLabel","frame":{"y":153,"x":91.333333333333329,"width":207.66666666666669,"height":40.666666666666657},"role_description":"","AXLabel":"Balance, £545,820.62","content_required":false,"type":"GenericElement","title":null,"help":null,"custom_actions":["Hide value"],"AXValue":null,"enabled":true,"role":"AXGenericElement","subrole":null},{"AXFrame":"{{126.33333333333333, 203.66666666666669}, {137.66666666666669, 18}}","AXUniqueId":"overdraftLabel","frame":{"y":203.66666666666669,"x":126.33333333333333,"width":137.66666666666669,"height":18},"role_description":"text","AXLabel":"Overdraft remaining","content_required":false,"type":"StaticText","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXStaticText","subrole":null},{"AXFrame":"{{164, 221.66666666666666}, {62, 18}}","AXUniqueId":null,"frame":{"y":221.66666666666666,"x":164,"width":62,"height":18},"role_description":"text","AXLabel":"£500.00","content_required":false,"type":"StaticText","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXStaticText","subrole":null},{"AXFrame":"{{309, 163.33333333333334}, {19.666666666666686, 20}}","AXUniqueId":"addMoneyBtn","frame":{"y":163.33333333333334,"x":309,"width":19.666666666666686,"height":20},"role_description":"button","AXLabel":"Add Money","content_required":false,"type":"Button","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXButton","subrole":null},{"AXFrame":"{{72, 334.33333333333331}, {246, 245.99999999999994}}","AXUniqueId":null,"frame":{"y":334.33333333333331,"x":72,"width":246,"height":245.99999999999994},"role_description":"text","AXLabel":"Spent £26.38 in September","content_required":false,"type":"StaticText","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXStaticText","subrole":null},{"AXFrame":"{{0, 675}, {390, 31}}","AXUniqueId":null,"frame":{"y":675,"x":0,"width":390,"height":31},"role_description":"slider","AXLabel":null,"content_required":false,"type":"Slider","title":null,"help":null,"custom_actions":[],"AXValue":"page 1 of 2","enabled":true,"role":"AXSlider","subrole":null},{"AXFrame":"{{0, 705}, {390, 56}}","AXUniqueId":"feedSlideBtn","frame":{"y":705,"x":0,"width":390,"height":56},"role_description":"","AXLabel":"Transactions, lowered position","content_required":false,"type":"GenericElement","title":null,"help":"Double tap to raise","custom_actions":[],"AXValue":null,"enabled":true,"role":"AXGenericElement","subrole":null},{"AXFrame":"{{0, 761}, {390, 83}}","AXUniqueId":null,"frame":{"y":761,"x":0,"width":390,"height":83},"role_description":"group","AXLabel":"Tab Bar","content_required":false,"type":"Group","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXGroup","subrole":null}]
`

**Comment by dmitry-zaitsev** [comment]
Unfortunately it does not seem like system reports any accessibility information for the tab items.

Could you try this solution to see if elements start appearing in the final result? https://stackoverflow.com/a/49437988/926907

**Comment by simon-gilmurray** [comment]
I've enabled `isAccessibilityElement` to be true for all of the TabBar buttons and even the overall TabBar itself (and confirmed the setting using Sherlock) and they're still not appearing in `hierarchy` or `idb ui` - I'll keep exploring, but if you have any other ideas, that would be great.

**Comment by mauriciomeirelles** [comment]
Unfortunately this is also happening for me with TabBar and NavBar buttons 😞
Looks like this is an issue with `idb` actually, more here: https://github.com/facebook/idb/issues/767
For now I'm using `tapOn` in a specific x,y.
```
- tapOn:
    point: 100,200

**Comment by simon-gilmurray** [comment]
@mauriciomeirelles Thanks I've added a comment to that issue. That is a temporary solution I guess, but would break as soon as you use a different device 😞

**Comment by dmitry-zaitsev** [comment]
Based on idb thread that @mauriciomeirelles what we can try as a (hopefully) temporary workaround is also probe points within each `group` in hope to find more views there. That might not work in every case, but it at least supposed to handle cases like nav bars

**Comment by dmitry-zaitsev** [comment]
We have released an experimental fix for this issue in 1.8.0. Please let us know if it works and attack `idb ui describe-all` output if it doesn't

**Comment by simon-gilmurray** [comment]
@dmitry-zaitsev thanks for attempting a fix, it looks to be making progress, but still not working properly:

> maestro hierarchy

` "attributes" : {
      "text" : "Tab Bar",
      "bounds" : "[0,761][390,844]"
    },
    "children" : [ ],
    "clickable" : null
  }, {
    "attributes" : {
      "bounds" : "[0,0][0,0]"
    },
    "children" : [ ],
    "clickable" : null
  }, {
    "attributes" : {
      "text" : "Tab Bar",
      "bounds" : "[0,761][390,844]"
    },
    "children" : [ ],
    "clickable" : null
  }, {
    "attributes" : {
      "text" : "Tab Bar",
      "bounds" : "[0,761][390,844]"
    },
    "children" : [ ],
    "clickable" : null
  }, {
    "attributes" : {
      "text" : "Tab Bar",
      "bounds" : "[0,761][390,844]"
    },
    "children" : [ ],
    "clickable" : null
  }, {
    "attributes" : {
      "text" : "Tab Bar",
      "bounds" : "[0,761][390,844]"
    },
    "children" : [ ],
    "clickable" : null
  }, {
    "attributes" : {
      "bounds" : "[0,0][0,0]"
    },
    "children" : [ ],
    "clickable" : null
  } ],
  "clickable" : null`


> idb ui describe-all

`,{"AXFrame":"{{0, 761}, {390, 83}}","AXUniqueId":null,"frame":{"y":761,"x":0,"width":390,"height":83},"role_description":"group","AXLabel":"Tab Bar","content_required":false,"type":"Group","title":null,"help":null,"custom_actions":[],"AXValue":null,"enabled":true,"role":"AXGroup","subrole":null}]`

**Comment by simon-gilmurray** [comment]
After updating simulators to iOS16, I can now see the TabBar elements via text (although their resource-ids are missing.
Unfortunately iOS16 crashes idb everytime :(

**Comment by a7medev** [comment]
I have the same issue, but there's something really weird: when I open Appium Inspector and start the Appium sever and then rerun Maestro tests it works!

**Comment by bitcrumb** [comment]
I made some observations which I documented on the Slack channel [here](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1670405706039299).

They could lead to a fix for the first tab not being visible on iOS 16.

/cc @dmitry-zaitsev
