### ISSUE TITLE
IOS - Facing Device not found And also getting this bellow response 

### ISSUE THREAD

**Issue by Abhilash-R-Flipkart** [mobile-dev-inc/maestro#275]
dyld: lazy symbol binding failed: can't resolve symbol _$sScCMa in /usr/local/Cellar/idb-companion/1.1.8/bin/../Frameworks/IDBGRPCSwift.framework/Versions/A/IDBGRPCSwift because dependent dylib @rpath/libswift_Concurrency.dylib could not be loaded
dyld: can't resolve symbol _$sScCMa in /usr/local/Cellar/idb-companion/1.1.8/bin/../Frameworks/IDBGRPCSwift.framework/Versions/A/IDBGRPCSwift because dependent dylib @rpath/libswift_Concurrency.dylib could not be loaded
fish: Job 1, 'idb_companion --udid 8C6D868E...' terminated by signal SIGABRT (Abort)

**Comment by dialex** [comment]
I had to install idb_companion, see https://maestro.mobile.dev/getting-started/installing-maestro#connecting-to-your-device

**Comment by dmitry-zaitsev** [comment]
We believe that the issue should be resolved in the latest Maestro version

**Comment by tajchert** [comment]
@dmitry-zaitsev  I have:
```
Maestro 1.19.0
MacOS 13.1
Xcode 14.1
Simulator - iPhone 14 Pro, iOS 16.1
```

And I'm still getting this error, however on other very same spec machine (simulator also, xcode, Maestro as well) I don't have this issue at all.
```
java.io.IOException: Cannot run program "idb_companion": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at maestro.cli.device.DeviceService.startIdbCompanion(DeviceService.kt:96)
	at maestro.cli.device.DeviceService.prepareDevice(DeviceService.kt:73)
	at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:[26](https://gitlab.com/eobuwie/mobile-apps/qa/eobuwie-maestro/-/jobs/3603937317#L26))
	at maestro.cli.session.MaestroSessionManager.selectDevice(MaestroSessionManager.kt:93)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:50)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:97)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:122)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:[27](https://gitlab.com/eobuwie/mobile-apps/qa/eobuwie-maestro/-/jobs/3603937317#L27)1)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 17 more
```

**Comment by tajchert** [comment]
`maestro studio` results in same error (probably not surprising as issue is with installing `adb_companion`.
Erasing Simulator - still same error.
Different device (iPhone 14, iOS 16.1) - same error.

**Comment by dmitry-zaitsev** [comment]
Could you make sure you have idb tool installed? It appears to be missing

**Comment by tajchert** [comment]
Yes, after manually adding `idk` (as per manual) it works fine @dmitry-zaitsev  

I understood 

> We believe that the issue should be resolved in the latest Maestro version

That it means Maestro since 1.19.0 will automatically install idk under the hood without manual install. Sorry if I misunderstood it.
