### ISSUE TITLE
Unrecognized field "flows" when uploading to maestro cloud

### ISSUE THREAD

**Issue by matt-dalton** [mobile-dev-inc/maestro#811]
It's possible I'm doing something wrong here, but I have a directory structure like this:
```
.maestro/
     Tests/
           TestFolder1/
                  myFlow.yaml
           TestFolder2/
                  myOtherFlow.yaml
     config.yaml
```

In my config.yaml:
```
baselineBranch: main
flows:
    - Tests/TestFolder1/*
    - Tests/TestFolder2/*
```

This allows me to organise my suites in sub-folders, and I can then easily run the tests with `maestro test .maestro/ `

If I then try and upload this to Maestro cloud (using `maestro cloud --apiKey [key] /Users/.../myApp.app .maestro/`), I get this error:
```
Upload request failed (400): Syntax error: Invalid config syntax: Unrecognized field "flows" (class api.workspace.TopLevelConfiguration), not marked as ignorable (5 known properties: "notifications", "appSize", "appStartup", "baselineBranch", "memoryLeaks"])
 at [Source: (jdk.nio.zipfs.ZipFileSystem$3); line: 5, column: 1] (through reference chain: api.workspace.TopLevelConfiguration["flows"])
```
It sounds like cloud doesn't understand my `flows` field. The [docs](https://maestro.mobile.dev/cli/test-suites-and-reports#inclusion-patterns) seem to suggest this pattern is supported by cloud.

Am I doing something wrong or is this a bug?

**Comment by igorsmotto** [comment]
It seems to be a bug.

**Comment by igorsmotto** [comment]
Fix was released. Maestro Cloud should now recognize "flows" field

**Comment by matt-dalton** [comment]
Hmmm...is there anything we have to do to get this fix? I'm still getting the bug, and it doesn't look like there's a new version after 1.23.0.

Will it be out in the next CLI version @igorsmotto?

**Comment by igorsmotto** [comment]
Hey @matt-dalton, could you try again?

No. Deploy was completed just now on Maestro Cloud. Maestro CLI is unnafected.

**Comment by matt-dalton** [comment]
Works! Thanks. Sorry too quick off the mark there.
